#
# dotphiles : https://github.com/dotphiles/dotphiles
#
# Defines environment variables.
#
# Authors:
#   Ben O'Hara <bohara@gmail.com>
#

# Set the path to dotzsh.
export DOTZSH="$HOME/.zsh"

# Source environment settings
source "$DOTZSH/env.zsh"

# Customize to your needs...
export ZSH=$HOME/.oh-my-zsh
export ZSH_THEME="robbyrussell"

export EDITOR=`which vim`


alias up='sudo softwareupdate -i -a && brew update && brew upgrade &&  upgrade_oh_my_zsh && cd /usr/local/Cellar/clisp/2.49/share/vim/vim73 && aap fetch && cd - && vim +BundleInstall! +qall! && clear'
alias glog="git log --graph --pretty=format:'%Cred%h%Creset %an: %s - %Creset %C(yellow)%d%Creset %Cgreen(%cr)%Creset' --abbrev-commit --date=relative"
alias t="nocorrect tmuxinator"
alias grunt="nocorrect grunt"
alias isup="nocorrect isup"
alias nave='nocorrect nave'
alias tmux='nocorrect tmux'
alias htop='nocorrect htop'
alias vimrc='vim $HOME/.vimrc'
alias rar='nocorrect rar'
alias brwe='brew'
alias e='exit'
alias b='brew'
alias v='vim'

#report cpu-/system-/user-time of commands running longer than 5 seconds
REPORTTIME=6

# enable tmuxinator
[[ -s $HOME/.tmuxinator/scripts/tmuxinator ]] && source $HOME/.tmuxinator/scripts/tmuxinator ]]

# Load RVM into a shell session *as a function*
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

# Start a server in the current directory
function server() {
  local port="${1:-8000}"
  open "http://localhost:${port}/"
  python -m SimpleHTTPServer "$port"
}

. `brew --prefix`/etc/profile.d/z.sh
function precmd () {
 z --add "$(pwd -P)"
}


source $ZSH/oh-my-zsh.sh
